# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import carro_pb2 as carro__pb2


class CarroServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.calcularValorTotal = channel.unary_unary(
                '/carro.CarroService/calcularValorTotal',
                request_serializer=carro__pb2.CarroRequest.SerializeToString,
                response_deserializer=carro__pb2.CarroResponse.FromString,
                )


class CarroServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def calcularValorTotal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CarroServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'calcularValorTotal': grpc.unary_unary_rpc_method_handler(
                    servicer.calcularValorTotal,
                    request_deserializer=carro__pb2.CarroRequest.FromString,
                    response_serializer=carro__pb2.CarroResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'carro.CarroService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CarroService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def calcularValorTotal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/carro.CarroService/calcularValorTotal',
            carro__pb2.CarroRequest.SerializeToString,
            carro__pb2.CarroResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
